version = 0.1

[staging.deploy.parameters]
stack_name = "api-staging"
s3_prefix = "api-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1golj62cuecmm"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []

[production.deploy.parameters]
stack_name = "api"
s3_prefix = "api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1golj62cuecmm"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
