name: Staging - Deploy SAM

on: workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
            - uses: aws-actions/setup-sam@v2
            - uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Install dependencies
              working-directory: ./packages/api/sam/lambda
              run: yarn --silent --frozen-lockfile
            - name: Deploy AWS SAM
              working-directory: ./packages/api
              run: |
                  yarn build
                  sam deploy --config-env staging --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides='EnvironmentParameter=Staging DynamoDBRegionParameter=${{secrets.DYNAMODB_REGION}} FullApiDomainNameParameter=${{secrets.STAGING_FULL_API_DOMAIN_NAME}} FullDomainNameParameter=${{secrets.STAGING_FULL_DOMAIN_NAME}} GoogleOauthClientIDParameter=${{secrets.GOOGLE_OAUTH_CLIENT_ID}} GoogleOauthIOSClientIDParameter=${{secrets.GOOGLE_OAUTH_IOS_CLIENT_ID}} GoogleOauthAndroidClientIDParameter=${{secrets.GOOGLE_OAUTH_ANDROID_CLIENT_ID}} GoogleOauthClientSecretParameter=${{secrets.GOOGLE_OAUTH_CLIENT_SECRET}} OpenAISecretKeyParameter=${{secrets.OPEN_AI_SECRET_KEY}}'
